### ISSUE TITLE
Add framed web view and share with terminal and help viewer

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder-reports#11]

**Comment by rlaverde** [comment]
We could maybe create a section in the spyder api for some helper widgets/functions?

**Comment by goanpeca** [comment]
Yes exactly what I had in mind. I think we should only allow importing from api when doing a plugin. If we need access to extra utils, we should have this available from within the api module, that way we have control of what we expose to the users, plus we can keep these shims in sync for newer apis, even if the original funcs/helpers are not available.
