### ISSUE TITLE
Missing packages on Windows

### ISSUE THREAD

**Issue by mmeierer** [spyder-ide/spyder-reports#18]
When trying to install the package on Win64 I get the following error message:

```
conda install spyder_reports -c spyder-ide
Fetching package metadata .............

PackageNotFoundError: Package missing in current win-64 channels:
  - spyder_reports
```

I would be great to specifiy which plattforms are currently supported. 

BTW, thanks for the great initiative. This plugin really adds value to Spyder.

**Comment by ccordoba12** [comment]
There are no packages for this plugin yet. Besides, it'll be usable only after we release Spyder 3.2, because that will be the first version with Markdown support.

So if you want to use this right now, you need to use Spyder and this plugin from git.

**Comment by rlaverde** [comment]
Closing because the first release is out 😄 https://github.com/spyder-ide/spyder-reports/releases
