### ISSUE TITLE
Error at startup when opening welcome.html

### ISSUE THREAD

**Issue by rlaverde** [spyder-ide/spyder-reports#34]
This error only happen sometimes, I haven't found a way to reproduce it

```
<spyder.otherplugins._ModuleMock object at 0x7f5c7c09ba90>: [Errno 2] No such file or directory: '/tmp/welcome.html'
Traceback (most recent call last):
  File "/home/rlaverde/code/spyder/spyder/app/mainwindow.py", line 915, in setup
    plugin.register_plugin()
  File "/home/rlaverde/anaconda3/envs/spyder/lib/python3.5/site-packages/spyder_reports/reportsplugin.py", line 93, in register_plugin
    self.report_widget.set_html_from_file(html_path)
  File "/home/rlaverde/anaconda3/envs/spyder/lib/python3.5/site-packages/spyder_reports/widgets/reportsgui.py", line 78, in set_html_from_file
    with codecs.open(filename, encoding="utf-8") as file:
  File "/home/rlaverde/anaconda3/envs/spyder/lib/python3.5/codecs.py", line 895, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/welcome.html'
```

**Comment by goanpeca** [comment]
When is this file being created?

**Comment by rlaverde** [comment]
At starting spyder, when the plugin is loaded

**Comment by goanpeca** [comment]
@rlaverde why not using the text directly, instead of opening a file?

**Comment by rlaverde** [comment]
The error is happening with the output file, I think Pweave only has the option to output to a file

**Comment by goanpeca** [comment]
Why is it being saved to that name then ? '/tmp/welcome.html'

**Comment by rlaverde** [comment]
the report is rendered in a temporal location https://github.com/spyder-ide/spyder-reports/blob/master/spyder_reports/reportsplugin.py#L87

**Comment by ccordoba12** [comment]
Yes, I changed that because in your initial work you tried to render the welcome file inside the package, and that's no possible when it's installed in a read-only location (e.g. `/usr/lib`).

However, I thought this was going to be fixed by using workers because the worker should wait until the file is available.

**Comment by rlaverde** [comment]
@ccordoba12 Yes, that's the solution, even when the error is raised the welcome.html is loaded

**Comment by ccordoba12** [comment]
Why an error should still be raised?

**Comment by rlaverde** [comment]
The thread loaded the output file, but when the register_plugin tries to load it again it could fail

**Comment by ccordoba12** [comment]
Right, that's why we have to remove those lines.
