### ISSUE TITLE
Use as basic structure, pylint plugin

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder-reports#4]
https://github.com/spyder-ide/spyder/tree/master/spyder_pylint

**Comment by rlaverde** [comment]
It'll be better to use https://github.com/spyder-ide/spyder-plugin-cookiecutter

**Comment by goanpeca** [comment]
@rlaverde yes, whatever but we need to create that. The template is not ready but you can use it now. The idea is to start doing that and not to wait to have a perfect template to fill in the project.

**Comment by rlaverde** [comment]
Yes, I'll update the PR with a template generated with the current state

**Comment by goanpeca** [comment]
:+1:
