### ISSUE TITLE
Release 0.1

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder-reports#51]
I think 0.1 is ready for a public release. I'll do the release this time, then @rlaverde will be in charge of it.

**Comment by ccordoba12** [comment]
@rlaverde, do you have time tomorrow after 6pm to have a videochat about this?

**Comment by rlaverde** [comment]
@ccordoba12 yes

**Comment by ccordoba12** [comment]
Ok, let's meet at 7:30 pm in appear.in/spyder. It'll take us half an hour to do the release.
