### ISSUE TITLE
Add Python 2 Support

### ISSUE THREAD

**Issue by rforgione** [spyder-ide/spyder-reports#55]
Hi there,

Based on the Pweave documentation, it looks like there is Python 2.7 support. I was a little confused when comparing this to the README which suggests that Python 3 is required since Pweave only works with Python 3. Would you mind clarifying?

**Comment by ccordoba12** [comment]
@rlaverde?

**Comment by goanpeca** [comment]
According to http://mpastell.com/pweave/

Features:
Python 2.7, 3.4 and 3.5 compatibility

**Comment by ccordoba12** [comment]
So until PWeave 0.3 is out we need to support Python 2. The thing is PWeave 0.3 only supports Python 3.

**Comment by ccordoba12** [comment]
@rlaverde, we need a **0.1.1** release for this. Also, we need to find all places where we use `str` and change them to `to_text_string`.

**Comment by rlaverde** [comment]
We develop this plugin with Pweave 0.3 in mind, as @ccordoba12 says it only supports python3

I thought the release of Pweave 0.3 will happen soon, Seeing at Pweave repo it looks like that the next version is almost ready, for that I decided to drop python2 support. 

> we need a 0.1.1 release for this. Also, we need to find all places where we use str and change them to to_text_string.

I'll work on this, also we need to add a container testing with python2.7

**Comment by goanpeca** [comment]
@rlaverde all of our plugins should be to the best extent as possible Py 27/ Py 35 and Py 36 compatible :-)

**Comment by ccordoba12** [comment]
> I'll work on this, also we need to add a container testing with python2.7

Yep, that's true too. I'll open a new container for that.
