### ISSUE TITLE
spyder 5.05 issue - can't import pandas

### ISSUE THREAD

**Issue by dinosg** [spyder-ide/spyder-reports#87]
in Linux, upgraded to spyder 5.0.5, but errors result when executing import pandas as pd.
Downgraded back to 5.0.3
seems to work OK on OS X

**Comment by juliangilbey** [comment]
This looks like an issue with Spyder itself, not with the spyder-reports plugin.

**Comment by ccordoba12** [comment]
Yeah, it is. @dinosg, please open an issue here if you've been unable to solve your problem:

https://github.com/spyder-ide/spyder/issues
