### ISSUE TITLE
being able to change font colors in ipython console

### ISSUE THREAD

**Issue by kaare-mikkelsen** [spyder-ide/spyder-reports#89]
I know this has probably been requested numerous times, but I would just like to add my vote to the request for a way to change colors in the ipython console. I like having a light background, but that makes in particular the light green colors in error messages really hard to read. 
![image](https://user-images.githubusercontent.com/26253733/137904885-4ba78b74-2ffc-496e-9dac-3b74ea8e2c5f.png)

**Comment by ccordoba12** [comment]
Hey @kaare-mikkelsen, thanks for reporting. Unfortunately those colors are hard-coded at the moment in IPython, so we can't adjust them in Spyder. However, that will change in IPython 8, which will be released in a couple of months.

**Comment by ccordoba12** [comment]
By the way, if you want to report other issues about Spyder, the next time please do it here:

https://github.com/spyder-ide/spyder/issues

That's because this repository is about a third-party plugin called `Spyder-reports`.
